### ISSUE TITLE
Prune the blockchain size

### ISSUE THREAD

**Issue by Jzarecta** [petertodd/python-bitcoinlib#111]
I wonder if there is a way that I can specify the **prune** options to cap the size of the blockchain, I am running this on a vps and 1/2 GB of space wont be enough for running this wallet.
I read that you can prune bitcoind to a desired target size. Is this supported by the library?

**Comment by petertodd** [comment]
Pruning isn't something python-bitcoinlib does, it's something your local Bitcoin Core installation does; python-bitcoinlib does work with pruned nodes.
