### ISSUE TITLE
wheel installation failure with setuptools and install_requires

### ISSUE THREAD

**Issue by zdexter** [petertodd/python-bitcoinlib#117]
Not sure why yet, but `python-bitcoinlib==0.5.1` can't be installed via `install_requires`. Non-wheel packages (e.g. `0.3.0`) work fine.

#### Error
```
Installed /Users/myuser/code/pyb/venv/lib/python3.5/site-packages/UNKNOWN-0.0.0-py3.5.egg
Processing dependencies for UNKNOWN==0.0.0
Searching for python-bitcoinlib==0.5.1
Reading https://pypi.python.org/simple/python-bitcoinlib/
No local packages or working download links found for python-bitcoinlib==0.5.1
error: Could not find suitable distribution for Requirement.parse('python-bitcoinlib==0.5.1')
```

#### Environment
`setuptools==25.2.0`
`python==3.5.2`

#### Reproduction steps

* create setup.py:
```python3
from setuptools import setup

setup(
    install_requires=[
        'python-bitcoinlib==0.5.1'
    ]
)
```
* `python3 setup.py develop` or `python3 setup.py install`

**Comment by zdexter** [comment]
@petertodd perhaps could you provide an sdist for 0.5.1? that would be a very helpful interim solution until it can be determined why setuptools can't install the wheel.

**Comment by petertodd** [comment]
Weird. Sorry, I don't know much about python packaging.

I just packaged v0.6.0 actually, and I think I included a sdist with it properly.

**Comment by zdexter** [comment]
`python3 setup.py install` still fails - README.md is missing from MANIFEST.in. this should fix: https://github.com/petertodd/python-bitcoinlib/pull/118

**Comment by petertodd** [comment]
Let me know if 0.6.1 didn't fix this issue, closing.

**Comment by zdexter** [comment]
@petertodd 0.6.1 doesn't fix this unfortunately, just the missing README problem. AFAIK, setuptools does not support wheels in`install_requires`. would you mind providing an sdist for 0.6.1 and other releases going forward?

**Comment by kanzure** [comment]
```
python3 setup.py sdist upload
```

**Comment by petertodd** [comment]
@zdexter Uploaded! Will do in the future.
