### ISSUE TITLE
bitcoin.rpc.Proxy.gettransaction() is broken

### ISSUE THREAD

**Issue by yevhen-m** [petertodd/python-bitcoinlib#119]
bitcoin/rpc.py:486
```
try:
  r = self._call('gettransaction', b2lx(txid))
except JSONRPCError as ex:
  ...
```
Why is that `b2lx` call there? `txid` is already a hex-encoded hash, so this call is broken.

**Comment by petertodd** [comment]
In python-bitcoinlib's RPC interface, all calls take raw bytes-encoded txids like everything else does, not the hex-encoded hashes you're used to seeing in UI's.
