### ISSUE TITLE
gettransaction in testnet

### ISSUE THREAD

**Issue by hofuke** [petertodd/python-bitcoinlib#125]
My code:
`import bitcoin.rpc
bitcoin.SelectParams("testnet")

proxy_connection = bitcoin.rpc.Proxy("http://removed:removed@127.0.0.1:8332")
print(proxy_connection.gettransaction("269b22e789089b3acfef5f118a5b2c9856a70833756594c2c2a16f070b830147"))
`

> Traceback (most recent call last):
  File "1.py", line 5, in <module>
    print(proxy_connection.gettransaction("269b22e789089b3acfef5f118a5b2c9856a70833756594c2c2a16f070b830147"))
  File "/usr/local/lib/python2.7/dist-packages/bitcoin/rpc.py", line 537, in gettransaction
    (self.__class__.__name__, ex.error['message'], ex.error['code']))
IndexError: Proxy.getrawtransaction(): Invalid or non-wallet transaction id (-5)

But this is valid transaction in my wallet:

`/bitcoin-cli -rpcport=8332 -rpcuser=removed -rpcpassword=removed -rcphost=127.0.0.1 gettransaction 269b22e789089b3acfef5f118a5b2c9856a70833756594c2c2a16f070b830147`

> {
  "amount": 0.32500000,
  "confirmations": 13,
  "blockhash": "000000000000096e471b9be59549bf8727a503bb3d523251401e39e0784f0fc7",
  "blockindex": 4,
  "blocktime": 1476547966,
  "txid": "269b22e789089b3acfef5f118a5b2c9856a70833756594c2c2a16f070b830147",
  "walletconflicts": [
  ],
  "time": 1476544357,
  "timereceived": 1476544357,
  "bip125-replaceable": "no",
  "details": [
    {
      "account": "",
      "address": "mwwx3cCbQ7dkebnQvJXmQz9kXmsinZmAuG",
      "category": "receive",
      "amount": 0.32500000,
      "label": "",
      "vout": 0
    }
  ],
  "hex": "0100000001ea91ed302099e8d70642c99a1a37d76622ce0aad3dcff5210be59c551e086d55010000006a47304402206257f8907983096d242f29f7f71b88d48fe131a5151f21214b49818b1fb3620e02202818150ed9a2ed0edd3635094cb344c81a09f4bb970627d2100d9cfc9ed862f4012102b42288db695d2535dd79e98ada6a1a4d474a158f68056bdd7ce39cff57021f4effffffff0220e9ef01000000001976a914b43c34239cefd21d09110bb5769611af4fe3881688acd0570a0a000000001976a914dc0be39384c137dc8f310594c8db19705b1bf14f88ac00000000"
}

I believe there is some buggy check that decides the txid is not valid... I have already done some test and my conclusion is the bug is located in the lib as my code is pretty simple.

**Comment by kanzure** [comment]
```
# use little-endian hex to bytes
from bitcoin.core import lx, b2lx, x, b2x
import bitcoin.rpc
proxy = bitcoin.rpc.Proxy()
txid = "269b22e789089b3acfef5f118a5b2c9856a70833756594c2c2a16f070b830147"
proxy._call("gettransaction", txid)
proxy.gettransaction(lx(txid))
```

In python 2.7,

```
proxy.gettransaction("269b22e789089b3acfef5f118a5b2c9856a70833756594c2c2a16f070b830147")
```

... should cause an error like "Invalid or non-wallet transaction id (-5)". However, in python 3 the same line should cause an error like "TypeError: 'str' does not support the buffer interface".

Note how `b2lx` (used in `gettransaction`) does not complain about receiving a hex encoded string value in python 2.7. Test with `b2lx("269b22e789089b3acfef5f118a5b2c9856a70833756594c2c2a16f070b830147")` to see the difference between python versions. Your problem is data mangling and using ancient python.

Use `gettransaction(lx(txid))`.

**Comment by hofuke** [comment]
Thanks this worked. I knew the issue was related with b2lx but I was not sure how to fix it from my end. Thanks!
