### ISSUE TITLE
Cannot deserialize 13575b3cfd90f38c90b490624be3cdc89ba2fb4616dbcd2782a093495993cfa3 from testnet

### ISSUE THREAD

**Issue by ayeowch** [petertodd/python-bitcoinlib#131]
Using the current `master` @ https://github.com/petertodd/python-bitcoinlib/commit/2e4d51a482a4331d91de9bae2ab7be56229e664a, I am not able to get `CTransaction.deserialize` to return the expected txid as shown below.

The expected txid should be `13575b3cfd90f38c90b490624be3cdc89ba2fb4616dbcd2782a093495993cfa3` but python-bitcoinlib is returning `50492dffaa576f61788cc0cd38c7e5bdeff29ebf2f04b2768cc1cd993978ac65`.

**Test case:**
```
>>> from bitcoin import SelectParams
>>> from bitcoin.core import b2lx
>>> from bitcoin.core import CTransaction
>>> from bitcoin.core import x
>>> SelectParams('testnet')

>>> hexstr = "010000000001010000000000000000000000000000000000000000000000000000000000000000ffffffff2f035fa40d00044e157957044980b5030c7a8e775740030000000000000a636b706f6f6c0b2f416e7453747265616d2fffffffff0250fd5d13000000001976a914876fbb82ec05caa6af7a3b5e5a983aae6c6cc6d688ac0000000000000000266a24aa21a9ed9ef46e6c6ab6dc2b94a365b1bb12f8e1319090a7d260df3cc1d37ce0c29ce7c80120000000000000000000000000000000000000000000000000000000000000000000000000"
>>> tx = CTransaction.deserialize(x(hexstr), allow_padding=True)
>>> b2lx(tx.GetHash())
'50492dffaa576f61788cc0cd38c7e5bdeff29ebf2f04b2768cc1cd993978ac65'
```

**Reference:**
https://testnet.smartbit.com.au/tx/13575b3cfd90f38c90b490624be3cdc89ba2fb4616dbcd2782a093495993cfa3
https://testnet.smartbit.com.au/tx/13575b3cfd90f38c90b490624be3cdc89ba2fb4616dbcd2782a093495993cfa3/hex

**Comment by harding** [comment]
It appears that this is a segwit coinbase and that the hex string is taken from a segwit-enabled bitcoind but [python-bitcoinlib doesn't appear to support parsing BIP141 transactions](https://github.com/petertodd/python-bitcoinlib/pull/112).

If you need python-bitcoinlib, you could try using a pre-0.13.0 node possibly using a newer node as a [filter](https://bitcoincore.org/en/2016/10/27/segwit-upgrade-guide/#not-upgrading-1) (or help upgrade python-bitcoinlib for segwit).

**Comment by kanzure** [comment]
Doesn't this need https://github.com/petertodd/python-bitcoinlib/pull/112 first?

**Comment by ayeowch** [comment]
@harding @kanzure Going to close this for now as this does require https://github.com/petertodd/python-bitcoinlib/pull/112

**Comment by petertodd** [comment]
Sorry, #112 is on my todo list!
