### ISSUE TITLE
transaction deserialization fails

### ISSUE THREAD

**Issue by sbaks0820** [petertodd/python-bitcoinlib#134]
Attempting to deserialize the raw testnet transaction fails in 
```python
proxy.getrawtransaction('45aef1dd64639f40ddcb5a1a0e4f78f4bb690f0ebd3fa006b21111711dfc1050')
```
Specifically deserializing
`45aef1dd64639f40ddcb5a1a0e4f78f4bb690f0ebd3fa006b21111711dfc1050` with 
```python
CTransaction.deserialize(x('020000000001019f8ddb5d17be8c0ac3c2d26ad1818f5e879b2357e433009bb79817b319cc87040000000017160014aed670ec9a96f5f2bd6df6de7a54f165a02db67affffffff01d8e53c00000000001976a914f1921908f63d4f87d9551dd425fbea0c8edfeaaf88ac0247304402207de9a112c3e43534d5ac88f168bcbdff3fd26410681975ab34c15980fcf17fe502204dab21daae0fe600646c2d7a0a19eb30c84080cfc1bbe60886b768dc9130c6aa01210279f92b67674cba018f8f5ba64b69d3d931786d7d7f39dbda6ddce04a3245af0600000000'))
```
fails with
```python
bitcoin.core.serialize.DeserializationExtraDataError: Not all bytes consumed during deserialization
```

**Comment by sbaks0820** [comment]
Deserialization succeeds when `allow_paddins=True` is used. Can anyone explain why that is?

**Comment by afk11** [comment]
That's a segwit transaction, and unfortunately the library doesn't support it at this time. I know the pull request #112 does add serialization support, so maybe you should ping that thread since an identical issue was raised earlier this week.

**Comment by sbaks0820** [comment]
Oh, okay. Thanks!

**Comment by petertodd** [comment]
Also, see the v0.8.0 release notes for a workaround to make Bitcoin Core's RPC return non-segwit-serialized transactions: https://github.com/petertodd/python-bitcoinlib/blob/master/release-notes.md#v080
