### ISSUE TITLE
Support .cookie authentication

### ISSUE THREAD

**Issue by juestr** [petertodd/python-bitcoinlib#138]
It would be nice if .cookie authentication were supported in rpc.py BaseProxy, instead of erroring out if no rpcpassword can be found in the config file:

    if 'rpcpassword' not in conf:
        raise ValueError('The value of rpcpassword not specified in the configuration file: %s' % btc_conf_file)

**Comment by petertodd** [comment]
Have you seen v0.8.0? It now supports cookie authentication!

https://github.com/petertodd/python-bitcoinlib/blob/master/release-notes.md#v080

**Comment by juestr** [comment]
Thanks, I just got around installing opentimestamps-client via pip3, and it works perfectly now.
