### ISSUE TITLE
is this a bitcoind RPC wrapper or not

### ISSUE THREAD

**Issue by openalmeida** [petertodd/python-bitcoinlib#143]
Hi,

```README.md::Requirements``` may mention directly that:

https://github.com/petertodd/python-bitcoinlib
is a ```Stand Alone Pure Python Bitcoin Client``` or not.

thus, i am confused if i need to have a bitcoind daemon running as backend/server ?

**Comment by petertodd** [comment]
python-bitcoinlib is a library. It's neither a stand-alone Bitcoin client, nor is it just an RPC wrapper.

What it focuses on is low level primitives. It does provide the tooling that would let you write a Bitcoin client, but it's not by itself a Bitcoin client.

Similarly, it has an RPC module that makes it easy to use the Bitcoin Core RPC interface, but it's functionality isn't limited to RPC.

**Comment by openalmeida** [comment]
yep, it is a  library.

it means i can code pure Python lines based on python-bitcoinlib:
```
* for full function Bitcoin common use (
    - wallet
    - block explorer
    - blockchain analysis
  ), but just care about high level application logic,
  no RPC required and with native Python directly.

* python-bitcoinlib provide RPC module is just for compatible care ? (
  this make me confused and submit this issue)

* for miner use too (it will be full Satoshi Python binding,
  mentioned but with "In the future"),

* in other word, i can leave Bitcoin Core away (it write by C++)

* leave RPC (do things within self progress) away too

```

sorry for my poor English, am i clear ?
