### ISSUE TITLE
i run  code of "Proxy.getrawtransaction()" and hava a error of Use -txindex to enable blockchain transaction queries

### ISSUE THREAD

**Issue by axing1991** [petertodd/python-bitcoinlib#148]
i run  code of "Proxy.getrawtransaction()" and hava a error of   "Use -txindex to enable blockchain transaction queries"

**Comment by petertodd** [comment]
You need to add the txindex=1 option to your ~/.bitcoin/bitcoin.conf file and reindex.

The `getrawtransaction` RPC call requires a local txid index, which Bitcoin Core doesn't enable by default as it uses up a lot of storage space.
