### ISSUE TITLE
Support for other altcoins

### ISSUE THREAD

**Issue by sbaks0820** [petertodd/python-bitcoinlib#149]
I use python-bitcoinlib a lot and I use it on different altcoins that share the same serialization and network protocol like bitcoin-abc and litecoin. So, it would be awesome to have those coin params included in the main repository so it can be used for work in any altcoin. 

The fork I have of this repo has some of the added params for bitcoin-abc and litecoin. I want to see the option of other altcoins in this repo and will continue to add more to my fork. Is there any support for this from other users? 

It's barely an code added on but just makes this work better in an automated environment if I don't have to manually add my repository to python.

**Comment by afk11** [comment]
I don't think the desire to see other altcoins in here is universal, and this gets very tricky those coins do _anything_ different, like change the serialization format of transactions (blackcoin), changing the signature hash types (bitcoin cash), and so on.

You could maintain a fork that supports them, but asking it of people here seems a bit much. 

(Or you should just pull request it and see what happens)

**Comment by petertodd** [comment]
Altcoins should fork python-bitcoinlib explicitly to ensure the coin-specific differences are handled correctly; I won't be adding support for altcoins to python-bitcoinlib as it's not the focus of this library.

**Comment by teran-mckinney** [comment]
Sorry for being off topic. Couldn't find any better communication mediums to use.

@sbaks0820 sorry to bug you, but I am interested in your changes for Bitcoin Cash support. I don't see any of your commits in your python-bitcoinlib fork. Is there any way you could push them up? Thank you!
