### ISSUE TITLE
rpc.py: authpair referenced before assignment (instantiating Proxy with conf file and service_url params)

### ISSUE THREAD

**Issue by adventurist** [petertodd/python-bitcoinlib#152]
When instantiating the Proxy class and providing an explicit location for the bitcoin.conf file
`        proxy = Proxy(btc_conf_file='/data/bitcoin/data/testnet3/bitcoin.conf', service_url='http://my-favourite-domain.com')
`
I encounter the following issue

>   File "/app/lib/python3.5/site-packages/bitcoin/rpc.py", line 189, in __init__
    authpair = authpair.encode('utf8')
UnboundLocalError: local variable 'authpair' referenced before assignment

It appears that conditions simply need to be set to read the authpair from the config file, even if service_url is being set.

**Comment by sr-gi** [comment]
The same happens when specifying a service url with auth on in, like:

http:user:pass@domain:port

With no config file.

**Comment by alfiedotwtf** [comment]
#153 should fix this

**Comment by petertodd** [comment]
Does this work for you now that #153 is merged?

**Comment by sr-gi** [comment]
Seems to work now for me.

**Comment by petertodd** [comment]
Great! Closing
