### ISSUE TITLE
issue with setuptools 

### ISSUE THREAD

**Issue by M0rningSt4r** [petertodd/python-bitcoinlib#155]
UserWarning: The version specified (u'0.9.0-PENDING') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.

**Comment by petertodd** [comment]
Fixed in https://github.com/petertodd/python-bitcoinlib/commit/2cd65b79a3e722f77c71cd26a6f805e62d3ada09

Thanks!
