### ISSUE TITLE
[BUG]Crash while running examples spend-p2pksh and spend-p2sh

### ISSUE THREAD

**Issue by sanket1729** [petertodd/python-bitcoinlib#158]
Hello,
   I was trying out some basic example scripts in the examples folder in this repository. There is crash while executing
`sighash = SignatureHash(txin_scriptPubKey, tx, 0, SIGHASH_ALL)`.

The error log is

> Traceback (most recent call last):
  File "C:/Bitcoin/p2sh.py", line 77, in <module>
    sighash = SignatureHash(txin_redeemScript, tx, 0, SIGHASH_ALL)
  File "C:\Users\sanket\AppData\Local\Programs\Python\Python36\lib\site-packages\bitcoin\core\script.py", line 1018, in SignatureHash
    assert not script.is_witness_scriptpubkey()
  File "C:\Users\sanket\AppData\Local\Programs\Python\Python36\lib\site-packages\bitcoin\core\script.py", line 683, in is_witness_scriptpubkey
    return 3 <= len(self) <= 42 and struct.unpack('<b',self[0])[0]
TypeError: a bytes-like object is required, not 'int'

This is directly related to PR https://github.com/petertodd/python-bitcoinlib/commit/5cd34672d7085ca4d55693a1008101c02ceeb7e9 . My suspicion based on the discussion for bug in thread for #112, is that the PR fixed a bug for python2, but introduced a reverse bug(byte[] instead of int) one for python 3. However, If I undo https://github.com/petertodd/python-bitcoinlib/commit/5cd34672d7085ca4d55693a1008101c02ceeb7e9 directly in source, it works correctly and there is no error.

How to reproduce?
Simply run spend-p2pksh or spend-p2sh examples on python3 with no other changes

Version: Latest Pypi release(0.9.0) 
OS: Windows 10
python3.6

**Comment by sanket1729** [comment]
This problem is not present in release 0.8.0 . But it is bug in 0.9. I have successfully reproduced this Centos, and Ubuntu distros

**Comment by ayalaio** [comment]
I have the fix here:
https://github.com/petertodd/python-bitcoinlib/pull/159/files

**Comment by ysangkok** [comment]
@afk11 I think this can be closed, the linked fix PR by @ayalaio was merged.

**Comment by sanket1729** [comment]
Closing
