### ISSUE TITLE
"This library may go unmaintained in the near future"

### ISSUE THREAD

**Issue by dgpv** [petertodd/python-bitcoinlib#192]
As said by Bryan Bishop (with reference to Peter Todd), in his talk at Bitcoin Edge Dev++ 2018: http://diyhpl.us/wiki/transcripts/scalingbitcoin/tokyo-2018/edgedevplusplus/python-bitcoinlib/ or
https://www.youtube.com/watch?v=iPt2ekHoEy8&t=8320 (time mark: 02:18:37)

This library may go unmaintained in the near future, or already has.

Let's make a list of maintained forks or derivatives here, for reference.

**Comment by dgpv** [comment]
We plan to maintain a derivative of the library, but with all bitcoin network-related code stripped from it (bitcoin/bloom.py, bitcoin/messages.py, bitcoin/net.py), so we changed the name to python-bitcoindata, to avoid confusion.

https://github.com/Simplexum/python-bitcoindata

We may also change the python package name to 'bitcoindata', to avoid conflicts, deprecate RPC functions, and make signing with libsecp256k1 the default. (issues on this:https://github.com/Simplexum/python-bitcoindata/issues/7  https://github.com/Simplexum/python-bitcoindata/issues/8  https://github.com/Simplexum/python-bitcoindata/issues/9)

If someone is willing to maintain the full library as it is, we may use their fork, instead.

**Comment by kanzure** [comment]
I am also interested in a status update.

**Comment by petertodd** [comment]
> I am also interested in a status update.

Been busy with other (paying) stuff right now; no-one is paying me to work on this right now.

I'm dubious about just handing it over to someone else, as I think it's better that people make a conscious decision to change who they trust.

**Comment by dgpv** [comment]
So the library in fact did not go 'unmaintained'. This issue can be closed now, I suppose.

**Comment by petertodd** [comment]
Well, it's somewhat maintained at least. :)

**Comment by dbolser** [comment]
Thanks for maintaining Peter!

**Comment by petertodd** [comment]
> Thanks for maintaining Peter!

Thanks for everyone else submitting pull-reqs - they're doing the real work. :)
