### ISSUE TITLE
Running CECKey.set_secretbytes twice causes an exception the second time

### ISSUE THREAD

**Issue by Flavien** [petertodd/python-bitcoinlib#20]
Running `CECKey.set_secretbytes` twice causes an exception the second time. Easy to repro:

    import bitcoin.wallet

    bitcoin.SelectParams('regtest')

    private_key = bitcoin.wallet.CBitcoinSecret('cUgetboAcBhZyma6SvFHhefkw9nVnTpcpswePM5YRv2GqMjrqSgR')
    private_key = bitcoin.wallet.CBitcoinSecret('cR2rg2NFZdWZ3jdAdLwaKCPhL5CTBVBfunRz2a8xuJkyBccceojj')

The stack trace is:

        private_key = bitcoin.wallet.CBitcoinSecret('cR2rg2NFZdWZ3jdAdLwaKCPhL5CTBVBfunRz2a8xuJkyBccceojj')
      File "...\lib\site-packages\bitcoin\wallet.py", line 238, in __init__
        CKey.__init__(self, self[0:32], len(self) > 32 and bord(self[32]) == 1)
      File "...\lib\site-packages\bitcoin\wallet.py", line 206, in __init__
        self._cec_key.set_secretbytes(secret)
      File "...\lib\site-packages\bitcoin\core\key.py", line 58, in set_secretbytes
        if not ssl.EC_POINT_mul(group, pub_key, priv_key, None, None, ctx):
    OSError: exception: access violation reading 0x00007FFE0120F9C4

This happens on Windows, seems to work fine on Linux.

**Comment by petertodd** [comment]
I believe this is fixed as of v0.5.0
