### ISSUE TITLE
signrawtransaction is deprecated and will be removed from bitcoind v0.18

### ISSUE THREAD

**Issue by remyers** [petertodd/python-bitcoinlib#201]
I ran into this issue with the following code:

> txout = CMutableTxOut(sats, CBitcoinAddress(addr).to_scriptPubKey())
> unfunded_transaction = CMutableTransaction([], [txout])
> funded_transaction = proxy.fundrawtransaction(unfunded_transaction)
> **signed_transaction = proxy.signrawtransaction(funded_transaction["tx"])**

If I change signrawtransaction  in rpc.py to use "signrawtransactionwithwallet" instead of "signrawtransaction" then it works. I'm not sure though if there's some subtly I'm missing here.  Happy to do a PR if that's all that's needed though.

Full back trace if it helps:
> txTenna>sendtoaddress_mesh 2N24yKP5QCpV7c2SBRddmAbsMaCfCfwds18 100000
> Traceback (most recent call last):
>   File "/Users/richard/Documents/proxy/PublicSDK/python-public-sdk/txtenna.py", line 1080, in do_sendtoaddress_mesh
>     signed_transaction = proxy.signrawtransaction(funded_transaction["tx"])
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/bitcoin/rpc.py", line 679, in signrawtransaction
>     r = self._call('signrawtransaction', hextx, *args)
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/bitcoin/rpc.py", line 231, in _call
>     raise JSONRPCError(response['error'])
> **JSONRPCError: {u'message': u'signrawtransaction is deprecated and will be fully removed in v0.18. To use signrawtransaction in v0.17, restart bitcoind with -deprecatedrpc=signrawtransaction.\nProjects should transition to using signrawtransactionwithkey and signrawtransactionwithwallet before upgrading to v0.18', u'code': -32}**
> txTenna>Terminated: 15

**Comment by petertodd** [comment]
Yeah, that RPC interface is out of date and needs work, sorry.
