### ISSUE TITLE
Any chance of SIGHASH_NOINPUT being added per BIP-0118?

### ISSUE THREAD

**Issue by sidaudhi** [petertodd/python-bitcoinlib#202]
Would be great if SIGHASH_NOINPUT was also available since I am trying to work on Eltoo transactions on a state-chain and having a tough time with Rust. Moving to python, this library seems to be the best one around.

**Comment by petertodd** [comment]
As `SIGHASH_NOINPUT` won't be added to this library unless it becomes a part of the standard Bitcoin protocol. I'd suggest you make your own fork instead.
