### ISSUE TITLE
rpc.RawProxy: guard against accessing python internal attributes does not work

### ISSUE THREAD

**Issue by dgpv** [petertodd/python-bitcoinlib#203]
https://github.com/petertodd/python-bitcoinlib/blob/7e191f03b0820ff84f7551747e6f084436631242/bitcoin/rpc.py#L290-L293

This check is useless because `__getattr__` is called only if there are no existing attributes with this name for an instance. Internal attributes are there already.

```
>>> from bitcoin.rpc import RawProxy
>>> p = RawProxy()
>>> p.__class__
<class 'bitcoin.rpc.RawProxy'>
```

To enforce this check, it should be checked within `__getattribute__`:

```
    def __getattribute__(self, name):                                           
        if name.startswith('__') and name.endswith('__'):                       
            # Python internal stuff                                             
            raise AttributeError                                                
                                                                                
        return super(RawProxy, self).__getattribute__(name)                     
```

And within `__getattr__`, too, because doing `self._call('__blabla__')` does not make sense.

But there is a question: is this check needed at all? What failure mode it tries to prevent ?

It may be a problem if someone decides to do horribly insecure thing, and allow external user input to be used with it: `getattr(proxy, user_supplied_method_name)(*args)`, but this seems to be a much more convoluted way to do this, instead of just `proxy.call(user_supplied_method_name, *args)` - which is still horrible, but at least does not allow acces to internal python attrs.

Is there other failure modes possible ?

preveinting access to internal attributes would prevent access not only to dangerous things like `__setattr__` , but also to useful things like `__doc__`.

Is this potential misuse case worth adding this protection?

**Comment by petertodd** [comment]
I think my intent with that check was just make clear that none of the RPC calls would match the reserved `__*__` pattern, raising an AttributeError unconditionally.

Since it is a `__getattr__` check, the actual existing stuff like `__doc__` can be accessed.

**Comment by dgpv** [comment]
Ah, so the idea is that an access to non-existing or mistyped internal attribute won't cause the RPC call. If my understanding is correct, this issue can be considered resolved.

**Comment by petertodd** [comment]
Yup! I think that's what I was going for.

Lesson learned: comment your code. :) (heck, this would make a good first pull-req for a beginner!)
