### ISSUE TITLE
"Generate" regtest method deprecated and to be removed in v0.19

### ISSUE THREAD

**Issue by alexeiZamyatin** [petertodd/python-bitcoinlib#209]
The `generate` rpc call is deprecated and will be removed in v0.19. Bitcoin-cli message output when called:
`The wallet generate rpc method is deprecated and will be fully removed in v0.19. To use generate in v0.18, restart bitcoind with -deprecatedrpc=generate. Clients should transition to using the node rpc method generatetoaddress'`

Fix: `generate(self, numblocks)` in rpc.py (https://github.com/petertodd/python-bitcoinlib/blob/master/bitcoin/rpc.py#L383) needs to be updated to something along the lines of `generate(self, numblocks, address)`. 

Can make a PR if that helps.

**Comment by petertodd** [comment]
Fixed via #210
