### ISSUE TITLE
Parcial update of an HDWallet

### ISSUE THREAD

**Issue by Moliholy** [petertodd/python-bitcoinlib#215]
My use case is the following:

I am working for an exchange, and I am going to process in a backend service lots of orders per minute in bitcoin.

My original idea was to create a wallet per user ID so that users can send funds to their own "wallets". However I saw all methods to send/update require an `account_id` parameter, which seems to imply I cannot mix inputs from several accounts into a fat output whenever we have to collect the received money once every 1-2-3 hours. Am I correct? If so, is there something that could be done to fix it?

My second idea was to use a sole wallet (account 0) and create several addresses whenever a customer creates an order. It works fine, but when calling the `utxos_update` method it takes a very long time to update, until the point that the caller gets a request timeout with more than ~1000 generated addresses. After inspecting the code I realized this occurs because all addresses, including old ones, are again and again refreshed. I understand that my use case is pretty special and not valid for the vast majority of users, but wouldn't be a good idea to update the balances based on some criteria? Concretely, couldn't I just filter the addresses (keys) I'm interested in and update only those utxos? I know I can do that manually, but that implies SQL updates are made one by one and address queries to bitcoind are made one by one as well instead of five by five, which is pretty inefficient and slow. Could this be improved?

**Comment by dgpv** [comment]
These questions are mostly about Bitcoin Core wallet, and not about python-bitcoinlib.

I think this questions are better directed at bitcoin stackexchange https://bitcoin.stackexchange.com/

That said, was I faced similar questions long time ago, and the solution was to build special-purpose system that does its own address management, coin selection, secure signing with spending velocity control, etc... , and only relies on bitcoind for receiving and sending raw transactions. Bitcoin Core just does not have usecases of such high-transaction-volume services as a priority.

**Comment by Moliholy** [comment]
Thanks for the quick reply! I'll keep digging then 👍
