### ISSUE TITLE
Deterministic Signatures?

### ISSUE THREAD

**Issue by odonnellnoel** [petertodd/python-bitcoinlib#237]
Hello,

I seem to be getting a different signature every time I sign a transaction, could we integrate [deterministic signatures](https://tools.ietf.org/html/rfc6979#page-20) so the k is chosen deterministically?

It would be nice to have this as an option.

**Comment by dgpv** [comment]
There is already (albeit not the most convenient) way to use libsecp256k1 for signing, and it uses RFC6979: https://github.com/petertodd/python-bitcoinlib/pull/185

**Comment by odonnellnoel** [comment]
awesome, thanks.

**Comment by odonnellnoel** [comment]
Hi, I had a look at [https://github.com/petertodd/python-bitcoinlib/pull/185](#185) - I'm still a bit confused about how I'm supposed to turn this feature on.

If I try to import this `use_libsecp256k1_for_signing` function I cannot do so:
```
from bitcoin.core.key import use_libsecp256k1_for_signing
```

am I missing something here?

**Comment by dgpv** [comment]
```
from bitcoin.core.key import use_libsecp256k1_for_signing
use_libsecp256k1_for_signing(True)
```

works for me. What version are you using ? It was merged after v0.10.2 and is present in v0.11.0 and in master

**Comment by odonnellnoel** [comment]
I'm using 0.10.2.

Here's what I'm getting:

```
Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bitcoin
>>> bitcoin.__version__
'0.10.2'
>>> from bitcoin.core.key import use_libsecp256k1_for_signing
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'use_libsecp256k1_for_signing' from 'bitcoin.core.key' (/home/noel/.local/lib/python3.7/site-packages/bitcoin/core/key.py)
>>> use_libsecp256k1_for_signing(True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'use_libsecp256k1_for_signing' is not defined
>>> 
```

It looks like this function is not exporting during build. Anyhow, I'll upgrade and see if that helps.

**Comment by dgpv** [comment]
upgrading to v0.11.0 should help

**Comment by odonnellnoel** [comment]
It seems to work now Dmitry, many thanks!
