### ISSUE TITLE
How to query against all transactions involving a public key?

### ISSUE THREAD

**Issue by valexandersaulys** [petertodd/python-bitcoinlib#249]
How do I query for all transactions involving the public key of a wallet?

Assume I have a running bitcoin node.

Thanks in advance,
Vincent

**Comment by dgpv** [comment]
If you need the transactions associated with a wallet of your node (includeing watch-only addresses). then you can use rpc API to issue a `listtransactions` RPC command (and others, like `listreceivedbyaddress`).

If you need to get transactions associated with arbitrary address that is not tracked by your node, you'll need some sort of address index. Take a look at https://github.com/bitcoin/bitcoin/pull/14053 and https://github.com/romanz/electrs

This question does not seem to be bitcoinlib-specific, as you could in principle resolve it just using command-line tools.  I believe it is better to look for an answer for such questions at  https://bitcoin.stackexchange.com/

**Comment by valexandersaulys** [comment]
Was not aware that specific addresses needed to be tracked. I figured if I had every block then that would be enough.

The bitcoinlib cannot abstract these commands into python for me? I can only issue them via RPC?

**Comment by dgpv** [comment]
> I figured if I had every block then that would be enough.

No. Bitcoin PR 14053 referenced in my previous message have link to discussions about that.

> The bitcoinlib cannot abstract these commands into python for me? I can only issue them via RPC?

It wraps `listunspent`. But what you get is just an answer from `listunpent` processed and the components of the answer converted to library objects. The semantics is the same. No other `list*` commands are wrapped currently (the results will be returned directly as JSON for unwrapped commands, AFAIR)

**Comment by valexandersaulys** [comment]
Thank you for taking the time to reply with my newcomer question. 

I will mark this issue closed.
