### ISSUE TITLE
Request for http PaymentRequest and PaymentACK objects explanation

### ISSUE THREAD

**Issue by xiutxu** [petertodd/python-bitcoinlib#27]
The bip-00700-payment-protocol.py example shows how to generate an http PaymentRequest object and a PaymentACK object. 
Could you point me to documentation which explains the purpose of these objects? How do they relate to the spend-p2pkh-txout.py example?

**Comment by bellaj** [comment]
to get payments_pb2 
sudo apt install protobuf-compiler
`protoc -I=paymentrequest.proto_location --python_out=examples/paymentrequest.proto`
