### ISSUE TITLE
Question about where is wallet stored?

### ISSUE THREAD

**Issue by stephenoseiowusu** [petertodd/python-bitcoinlib#279]
I know you can store the wallet keys in a separate database but where is the actual wallet stored ?  What size are the wallets created if they are created?  Im sorry for asking this simple question but I ask this question on behalf of an organization I cannot name, we should have a crypto expert but we dont and we have to resort to this.... Just my job as a project manager / lead developer.

**Comment by michaelfolkson** [comment]
From [wallet.py](https://github.com/petertodd/python-bitcoinlib/blob/master/bitcoin/wallet.py)

```
Wallet-related functionality
Includes things like representing addresses and converting them to/from
scriptPubKeys; currently there is no actual wallet support implemented.
```
