### ISSUE TITLE
The default msg_version.strSubVer is bytes but the encoder expects a string.

### ISSUE THREAD

**Issue by llamasoft** [petertodd/python-bitcoinlib#287]
This appears to be caused by https://github.com/petertodd/python-bitcoinlib/commit/80fffb3c12582b283a351db55cdc39706649a04d

The default [msg_version.strSubVer](https://github.com/petertodd/python-bitcoinlib/blob/4b8fa0ced0b7b57fe5fe6254956d6db5fa934732/bitcoin/messages.py#L123-L124) value is created as _bytes_ but the serializer assumes that it will be a string.  This means that an instance of `msg_version` with default values can't actually be serialized.

```
  ...
  File "/lib/python/site-packages/bitcoin/messages.py", line 108, in stream_serialize
    data = self.to_bytes()
  File "/lib/python/site-packages/bitcoin/messages.py", line 55, in to_bytes
    self.msg_ser(f)
  File "/lib/python/site-packages/bitcoin/messages.py", line 163, in msg_ser
    VarStringSerializer.stream_serialize(self.strSubVer.encode(), f)
```

**Comment by petertodd** [comment]
Fixed.

**Comment by upintheairsheep** [comment]
Are you alive?
