### ISSUE TITLE
Sending tx does not work

### ISSUE THREAD

**Issue by pbies** [petertodd/python-bitcoinlib#292]
I tried examples with my own private key and address and seems like running a transaction (by bitcoin-cli) does just not work!

Mostly the error is:

error code: -25
error message:
bad-txns-inputs-missingorspent

**Comment by petertodd** [comment]
That error message means your transaction isn't valid because it tries to spend outputs that don't exist.

**Comment by pbies** [comment]
I am sure that the inputs are ok and with balance.

**Comment by petertodd** [comment]
Well you should investigate more because something is definitely wrong.

Are you sure your node is fully synced?

**Comment by pbies** [comment]
I am working on that already for two whole days - Friday and Saturday. Yes, Bitcoin Core is fully synced, it has the wallet that has the balance, the same address I am trying to use in the transaction and used script from examples just changing the input, output and balance to move the funds and still it does not work giving the above error. I tried two options - only one address and tried to do tx with two input addresses. Nothing works.

**Comment by pbies** [comment]
Script I am using:

`#!/usr/bin/env python3

import hashlib
import subprocess

from bitcoin import *
from bitcoin.core import *
from bitcoin.core.script import *
from bitcoin.core.scripteval import *
from bitcoin.wallet import *

SelectParams('mainnet')
seckey = CBitcoinSecret.from_secret_bytes(bytes.fromhex('my priv key in hex format'))
txid = lx('input tx in hex format') # lx! sure
vout = 5
txin = CMutableTxIn(COutPoint(txid, vout))
txin_scriptPubKey = CScript([OP_DUP, OP_HASH160, Hash160(seckey.pub), OP_EQUALVERIFY, OP_CHECKSIG])
txout = CMutableTxOut(77000, CBitcoinAddress('address I want to send funds to').to_scriptPubKey())
tx = CMutableTransaction([txin], [txout])
sighash = SignatureHash(txin_scriptPubKey, tx, 0, SIGHASH_ALL)
sig = seckey.sign(sighash) + bytes([SIGHASH_ALL])
txin.scriptSig = CScript([sig, seckey.pub])
VerifyScript(txin.scriptSig, txin_scriptPubKey, tx, 0, (SCRIPT_VERIFY_P2SH,))
r = subprocess.run(["/mnt/c/Program Files/Bitcoin/daemon/bitcoin-cli.exe", "sendrawtransaction", b2x(tx.serialize())])
`

**Comment by pbies** [comment]
I've done further work. Now the error is:
`bitcoin.core.scripteval.VerifyOpFailedError: EvalScript: OP_EQUALVERIFY failed`
Which is strange, because I've given:
1. priv key hex (the same as always for my input address)
2. another txid for that priv key, I've made movement on that address
3. pubkey as above and separately as Hash160(x('...')), tested compressed and uncompressed
4. another destination address

I suspect that there may be some problem with x('...') and lx('...') which it could be that I am not using right.

**Comment by pbies** [comment]
I solved this problem by once again setting tx=... with the same variables as earlier when creating tx.
