### ISSUE TITLE
Add OP_CHECKLOCKTIMEVERIFY

### ISSUE THREAD

**Issue by btcdrak** [petertodd/python-bitcoinlib#34]

**Comment by kaykurokawa** [comment]
Just adding a note here that scripteval.py doesn't handle OP_CHECKLOCKTIMEVERIFY , it just treats it the same as it was when it was OP_NOP2..

**Comment by dgpv** [comment]
Maintaining compatible interpreter is a lot of work. For some tasks, using wrapping a call to libbitcoinconsensus library might be sufficient. (Example:  https://github.com/Simplexum/python-bitcointx/blob/master/bitcointx/core/bitcoinconsensus.py)

**Comment by petertodd** [comment]
Closing, because using libbitcoinconsensus is a better idea.
