### ISSUE TITLE
pip package out-of-date? (should be 0.3.0 instead of 0.2.1)

### ISSUE THREAD

**Issue by adamkrellenstein** [petertodd/python-bitcoinlib#36]
https://pypi.python.org/pypi/python-bitcoinlib

@Nassty is the maintainer, I believe?

**Comment by ouziel-slama** [comment]
Any news about this please ?
`pip` is buggy on Windows and people have to manually install `python-bitcoinlib`.
Thanks.

**Comment by adamkrellenstein** [comment]
+1 This is a pain for us over at Counterparty, and very easy to fix.

@Nassty, @petertodd

**Comment by petertodd** [comment]
Adam: I'm in SF for another two weeks with a busy schedule; want me to add you as a pip maintainer so you can do it?

I've never actually used pip and frankly don't know how it works.

**Comment by adamkrellenstein** [comment]
Thanks, but that's OK. We've worked around it. (PyPi isn't a lot of fun...)

**Comment by epheph** [comment]
@petertodd I'd be happy to maintain PyPi package, I see 0.3.0 still isn't uploaded.

**Comment by petertodd** [comment]
Great! What user name do I need to add on PyPi for you?

**Comment by epheph** [comment]
epheph

**Comment by petertodd** [comment]
@epheph Thanks! Just added you as a maintainer.

**Comment by epheph** [comment]
Great, uploaded v0.3.0 to PyPI . I'll keep an eye on new releases, but let me know if I fall behind

```
$ virtualenv tmp.venv
__SNIP__

$ ./tmp.venv/bin/pip install python-bitcoinlib
Downloading/unpacking python-bitcoinlib
  Downloading python-bitcoinlib-0.3.0.tar.gz (52kB): 52kB downloaded
  Running setup.py egg_info for package python-bitcoinlib

Installing collected packages: python-bitcoinlib
  Running setup.py install for python-bitcoinlib

Successfully installed python-bitcoinlib
Cleaning up...

lyra:~ scottb$ ./tmp.venv/bin/pip show python-bitcoinlib
---
Name: python-bitcoinlib
Version: 0.3.0
Location: .../tmp.venv/lib/python2.7/site-packages
Requires:

$ ./tmp.venv/bin/python
Python 2.7.9 (default, Dec 11 2014, 02:36:08)
[GCC 4.2.1 Compatible Apple LLVM 5.1 (clang-503.0.40)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import bitcoin
>>> dir(bitcoin)
['MainParams', 'RegTestParams', 'SelectParams', 'TestNetParams', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', 'absolute_import', 'bitcoin', 'core', 'division', 'params', 'print_function', 'unicode_literals']
```

**Comment by petertodd** [comment]
@epheph Just made a v0.4.0 release; if you could upload that to PyPi that'd be awesome!

**Comment by epheph** [comment]
v0.4.0 on pypi, thanks for letting me know.

**Comment by petertodd** [comment]
Awesome! Thanks a lot!
