### ISSUE TITLE
OpenSSL 1.0.1k handling of DER signatures

### ISSUE THREAD

**Issue by rnicoll** [petertodd/python-bitcoinlib#48]
The issue with OpenSSL 1.0.1k rejecting non-canonical signatures ( bitcoin/bitcoin#5634 ) presumably also affects python-bitcoinlib. I've attempted to patch this in https://github.com/rnicoll/python-bitcoinlib/commit/4015d4e4a5132014b8ac9c113f86a9c870e81709 although it's not working as-is, and I have run out of time to investigate right now.

Raising as an issue for awareness until I or someone else can produce a PR.

**Comment by petertodd** [comment]
Thanks! I noticed this too.

I'm going to also look into moving to using libsecp256k1, at least as an option.

**Comment by rnicoll** [comment]
Oops, completely forgot I didn't get this working, will take another look in a moment!

**Comment by rnicoll** [comment]
Found the issue, was passing in a pointer to a character array, instead of a pointer to a pointer to a character array. See #52.
