### ISSUE TITLE
Uploading python-bitcoinlib to pypi

### ISSUE THREAD

**Issue by Nassty** [petertodd/python-bitcoinlib#6]
Hey, have you considered uploading this lib to pypi? I'd like to do it if you don't mind (and if the last fixes pushed are included, it might involve a version bump from 0.1 to 0.1.1 maybe?)

**Comment by elichai** [comment]
why the new release isn't on pip?

**Comment by epheph** [comment]
@elichai A couple months after you asked, but v0.3.0 is on PyPI now. We can close this issue now.
