### ISSUE TITLE
Different return types for getblockhash, getbestblockhash

### ISSUE THREAD

**Issue by welshjf** [petertodd/python-bitcoinlib#73]
Confusingly, bitcoin.rpc.Proxy.getblockhash returns raw bytes, while getbestblockhash returns the hex string, as there's no wrapper implemented for the latter. And there's probably more like this, since as noted, object conversion is not fully implemented.

I guess the question is how much risk there is to existing code of fixing it now.

Perhaps, with a sufficiently major version bump to warn of the API breakage, we should get rid of the magic ``__getattr__`` in Proxy and de-underscore ``_call``. Thus, only explicitly wrapped RPCs can be called directly, while others can be called such as ``proxy.call("getbestblockhash")``. Ugly in that it kinda breaks the logic of calling it a "proxy" if you have to make such calls, but it allows new wrappers to be implemented compatibly.

**Comment by petertodd** [comment]
Hmm, I'm inclined to agree with you here re: getting rid of non-explicitly wrapped RPCs; we can make that part of the 0.5.0 release easily.

If you have the time, pull-reqs accepted. :)

**Comment by welshjf** [comment]
I realized this would make Proxy not actually a well-behaved subclass of RawProxy. Which is probably OK -- actually, it's kind of the point -- and to share the private methods we can make them both subclasses of BaseProxy.
