### ISSUE TITLE
Return argument for VerifyScript

### ISSUE THREAD

**Issue by benjiqq** [petertodd/python-bitcoinlib#94]
Would be nice if VerifyScript would return true if its valid, i.e. to have a function call which returns true or false (instead of throwing an error).

**Comment by petertodd** [comment]
Yeah, interesting question! I don't have too many examples of people using VerifyScript, so I'd like to see how people use it first prior to making a (API breaking) change.

Got any examples?

**Comment by benjyz** [comment]
There is the existing spend-p2pkh-txout example which uses a hardcoded txid. Instead I wanted to find the inputs from a given brainwallet and add the outputs. That is: create a brainwallet, compile a transaction, then verify the script, and if its valid, send it to the RPC.

work in progress here: https://github.com/benjyz/protomarket/tree/master/contract_tutorial
